---
- name: Nettoyage du r√©pertoire temporaire VLC
  ansible.windows.win_file:
    path: "{{ vlc_temp_dir }}"
    state: absent

- name: Nettoyage fini
  set_fact:
    package_message: "{{ package_message }} (cleanup OK)"
