- name: Gérer Notepad++ via Chocolatey
  hosts: windows
  gather_facts: false

  collections:
    - chocolatey.chocolatey

  tasks:
    - name: S'assurer que Chocolatey est installé
      win_chocolatey:
        name: chocolatey
        state: present

    - name: S'assurer que Notepad++ est à jour
      win_chocolatey:
        name: notepadplusplus
        state: latest

