---
- name: Test depuis Semaphore
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ping local
      ansible.builtin.ping:

    - name: S'assurer que htop est install√©
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: true
