---
- name: Test depuis Semaphore
  hosts: vm
  become: false  # on se connecte déjà en root

  tasks:
    - name: Ping VM
      ansible.builtin.ping:

    - name: S'assurer que htop est installé
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: true
