---
- name: "Force install notepad++"
  hosts: windows
  gather_facts: false
  vars_files:
    - ../roles/win_package_manager/vars/notepadplusplus.yml
  roles:
    - role: win_package_manager
      mode: force_install
      reboot: no
