---
- name: "Auto-update notepad++ if installed"
  hosts: windows
  gather_facts: false
  vars_files:
    - ../roles/win_package_manager/vars/notepadplusplus.yml
  roles:
    - role: win_package_manager
      mode: auto
      reboot: no
