---
- name: Force uninstall VLC
  hosts: windows
  gather_facts: false
  vars_files:
    - ../roles/win_package_manager/vars/vlc.yml
  roles:
    - role: win_package_manager
      mode: force_uninstall
      reboot: no
